export const langOptions = [
  { id: "en", language: "English" },
  { id: "hi", language: "Hindi" },
  { id: "es", language: "Spanish" },
];

export const lang = {
  en: {
    searchPlaceholder: "What would you like to watch today?",
    searchBtn: "Search",
    askGpt: "Ask GPT",
    browse: "Browse",
    userAuth: {
      signIn: "Sign In",
      signUp: "Sign Up",
      fullname: "Full Name",
      email: "Email address",
      password: "Password",
      alreadyMember: "Already a member? ",
      signInNow: "Sign in now.",
      newtoWebflix: "New to Webflix? ",
      signUpNow: "Sign Up now.",
      signOut: "SignOut",
    },
  },
  hi: {
    searchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    searchBtn: "खोज",
    askGpt: "जीपीटी से पूछें",
    browse: "ब्राउज़",
    userAuth: {
      signIn: "दाखिल करना",
      signUp: "साइन अप करें",
      fullname: "पूरा नाम",
      email: "मेल पता",
      password: "पासवर्ड",
      alreadyMember: "क्या पहले से ही सदस्य हैं? ",
      signInNow: "अब साइन इन करो।",
      newtoWebflix: "वेबफ़्लिक्स पर नए हैं? ",
      signUpNow: "अभी साइनअप करें।",
      signOut: "साइन आउट",
    },
  },
  es: {
    searchPlaceholder: "¿Qué te gustaría ver hoy?",
    searchBtn: "Buscar",
    askGpt: "Pregúntale a GPT",
    browse: "Navegar",
    userAuth: {
      signIn: "Iniciar sesión",
      signUp: "Inscribirse",
      fullname: "Nombre completo",
      email: "Dirección de correo electrónico",
      password: "Contraseña",
      alreadyMember: "¿Ya eres miembro? ",
      signInNow: "Inicia sesión ahora.",
      newtoWebflix: "¿Nuevo en Webflix? ",
      signUpNow: "Regístrate ahora.",
      signOut: "Desconectar",
    },
  },
};
